# -*- coding: utf-8 -*-
"""bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N_X-1aMDHdhNrYB3Nzk-Y78gP11Drz5n
"""

#!pip install python-telegram-bot python-dotenv

!pip install python-telegram-bot nest-asyncio

import os
import logging
from telegram import Update, ReplyKeyboardMarkup, ReplyKeyboardRemove
from telegram.ext import (
    Application,
    CommandHandler,
    ConversationHandler,
    MessageHandler,
    filters,
    ContextTypes,
)
from dotenv import load_dotenv

load_dotenv()

# Настройка логирования
logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)
logger = logging.getLogger(__name__)

# Состояния диалога
SELECT_SCALE, INPUT_PARAMS = range(2)

# Клавиатуры
SCALES_KEYBOARD = ReplyKeyboardMarkup(
    [
        ["🩺 SOFA", "💉 MODS"],
    ],
    one_time_keyboard=True
)

CANCEL_KEYBOARD = ReplyKeyboardMarkup([["❌ Отменить"]], one_time_keyboard=True)

# Параметры для шкал
SCALE_PARAMS = {
    "🩺 SOFA": [
        ("PaO2/FiO2 (мм рт.ст.)", "pao2_fio2", float),
        ("Тромбоциты (×10³/мкл)", "platelets", float),
        ("Билирубин (мг/дл)", "bilirubin", float),
        ("Среднее АД (мм рт.ст.)", "map", float),
        ("Шкала Глазго (3-15)", "glasgow", int),
        ("Креатинин (мг/дл)", "creatinine", float),
        ("Диурез (мл/сут)", "urine_output", float)
    ],
    "💉 MODS": [
        ("PaO2/FiO2 (мм рт.ст.)", "pao2_fio2", float),
        ("Билирубин (мг/дл)", "bilirubin", float),
        ("Креатинин (мг/дл)", "creatinine", float),
        ("Тромбоциты (×10³/мкл)", "platelets", float),
        ("Шкала Глазго (3-15)", "glasgow", int)
    ]
}

# Функции расчета баллов
def calculate_sofa(user_data):
    score = 0
    pao2_fio2 = user_data.get('pao2_fio2', 0)
    if pao2_fio2 >= 400: score +=0
    elif 300 <= pao2_fio2 < 400: score +=1
    elif 200 <= pao2_fio2 < 300: score +=2
    elif 100 <= pao2_fio2 < 200: score +=3
    else: score +=4

    platelets = user_data.get('platelets', 0)
    if platelets >=150: score +=0
    elif 100 <= platelets <150: score +=1
    elif 50 <= platelets <100: score +=2
    elif 20 <= platelets <50: score +=3
    else: score +=4

    bilirubin = user_data.get('bilirubin', 0)
    if bilirubin <1.2: score +=0
    elif 1.2 <= bilirubin <1.9: score +=1
    elif 2.0 <= bilirubin <5.9: score +=2
    elif 6.0 <= bilirubin <11.9: score +=3
    else: score +=4

    map_val = user_data.get('map', 0)
    gcs = user_data.get('glasgow', 15)
    score += 15 - gcs

    creatinine = user_data.get('creatinine', 0)
    urine = user_data.get('urine_output', 0)

    if creatinine <1.2: score +=0
    elif 1.2 <= creatinine <1.9: score +=1
    elif 2.0 <= creatinine <3.4: score +=2
    elif 3.5 <= creatinine <4.9: score +=3
    else: score +=4

    if urine >=500: score +=0
    elif 200 <= urine <500: score +=1
    else: score +=4

    return score

def calculate_mods(user_data):
    score = 0
    pao2_fio2 = user_data.get('pao2_fio2', 0)
    if pao2_fio2 <100: score +=3
    elif 100 <= pao2_fio2 <200: score +=2
    elif 200 <= pao2_fio2 <300: score +=1

    bilirubin = user_data.get('bilirubin', 0)
    if bilirubin >=6: score +=3
    elif 2 <= bilirubin <6: score +=1

    creatinine = user_data.get('creatinine', 0)
    if creatinine >=2: score +=2
    elif 1.2 <= creatinine <2: score +=1

    map_val = user_data.get('map', 0)
    if map_val <70: score +=2

    platelets = user_data.get('platelets', 0)
    if platelets <50: score +=2
    elif 50 <= platelets <100: score +=1

    gcs = 15 - user_data.get('glasgow', 15)
    score += gcs

    return score

# Обработчики диалога
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    await update.message.reply_text(
        "🏥 <b>Медицинский бот-ассистент</b>\n"
        "📊 Выберите шкалу для оценки:",
        reply_markup=SCALES_KEYBOARD,
        parse_mode="HTML"
    )
    return SELECT_SCALE

async def select_scale(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    user_choice = update.message.text

    if user_choice == "❌ Отменить":
        await cancel(update, context)
        return ConversationHandler.END

    if user_choice not in SCALE_PARAMS:
        await update.message.reply_text("❌ Неизвестная шкала")
        return ConversationHandler.END

    context.user_data.clear()
    context.user_data['scale'] = user_choice
    context.user_data['params'] = SCALE_PARAMS[user_choice]
    context.user_data['current_param'] = 0

    param_name = context.user_data['params'][0][0]
    await update.message.reply_text(
        f"📝 Первый параметр:\n{param_name}:",
        reply_markup=CANCEL_KEYBOARD
    )
    return INPUT_PARAMS

async def handle_parameter(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    try:
        if update.message.text == "❌ Отменить":
            await cancel(update, context)
            return ConversationHandler.END

        current = context.user_data['current_param']
        params = context.user_data['params']
        param_name, key, param_type = params[current]

        value = param_type(update.message.text)

        context.user_data[key] = value

        if current + 1 < len(params):
            context.user_data['current_param'] += 1
            next_param = params[current + 1][0]
            await update.message.reply_text(f"➡️ Следующий параметр:\n{next_param}", reply_markup=CANCEL_KEYBOARD)
            return INPUT_PARAMS
        else:
            return await show_results(update, context)

    except ValueError:
        error_msg = "❌ Ошибка формата. Введите число"
        await update.message.reply_text(error_msg, reply_markup=CANCEL_KEYBOARD)
        return INPUT_PARAMS

async def show_results(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    scale = context.user_data['scale']
    score = 0
    interpretation = ""

    # Расчет баллов
    if scale == "🩺 SOFA":
        score = calculate_sofa(context.user_data)
        if score < 6:
            interpretation = "🟢 Низкий риск (&lt;10&#37; летальности)"
        elif 6 <= score < 12:
            interpretation = "🟡 Средний риск (15-20&#37; летальности)"
        else:
            interpretation = "🔴 Высокий риск (&gt;95&#37; летальности)"

    elif scale == "💉 MODS":
        score = calculate_mods(context.user_data)
        if score <= 4:
            interpretation = "🟢 Легкая дисфункция"
        elif 5 <= score <= 8:
            interpretation = "🟡 Умеренная полиорганная недостаточность"
        else:
            interpretation = "🔴 Тяжелая полиорганная недостаточность"

    # Дополнительно
    interpretation = (
        interpretation
        .replace("%", "&#37;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )

    result_message = (
        f"📊 <b>Результаты оценки по шкале {scale}</b>\n\n"
        f"⭐ Накоплено баллов: <b>{score}</b>\n"
        f"📋 Интерпретация: {interpretation}\n\n"
        "🔄 Для нового расчета используйте /start"
    )

    await update.message.reply_text(
        result_message,
        parse_mode="HTML",
        reply_markup=ReplyKeyboardRemove()
    )
    context.user_data.clear()
    return ConversationHandler.END

async def cancel(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    await update.message.reply_text(
        "🚫 Текущая операция отменена. Для нового расчета нажмите /start",
        reply_markup=ReplyKeyboardRemove()
    )
    context.user_data.clear()
    return ConversationHandler.END

async def error_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    logger.error("Ошибка: %s", context.error, exc_info=True)
    await update.message.reply_text(
        "⚠️ Произошла техническая ошибка. Пожалуйста, попробуйте позже.",
        reply_markup=ReplyKeyboardRemove()
    )
    context.user_data.clear()

def main():
    TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
    if not TOKEN:
        logger.error("TELEGRAM_BOT_TOKEN не установлен")
        return

# Создаем и настраиваем приложение
application = Application.builder().token(TOKEN).build()

# Добавляем обработчики (автомат для управления многошаговым диалогом)
conv_handler = ConversationHandler(
    entry_points=[CommandHandler('start', start)],
    states={
        SELECT_SCALE: [MessageHandler(filters.TEXT & ~filters.COMMAND, select_scale)],
        INPUT_PARAMS: [MessageHandler(filters.TEXT & ~filters.COMMAND, handle_parameter)]
    },
    fallbacks=[CommandHandler('cancel', cancel)],
    allow_reentry=True
)

application.add_handler(conv_handler)
application.add_error_handler(error_handler)

PORT = int(os.environ.get("PORT", 8443))
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
        logger.info("Запуск в режиме вебхука")
        application.run_webhook(
            listen="0.0.0.0",
            port=PORT,
            url_path=TOKEN,
            webhook_url=f"https://{RENDER_EXTERNAL_HOSTNAME}/{TOKEN}"
        )
    else:
        logger.info("Запуск в режиме polling")
        application.run_polling()

if __name__ == '__main__':
    main()